language: java
jdk:
- oraclejdk8
sudo: required
services:
- docker

before_script:
# Install the Heroku CLI
- wget -qO- https://toolbelt.heroku.com/install.sh | sh
# Login to Docker Registries (Docker Hub and Heroku)
- echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
- echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
# Change directories down into the releng package for the Maven build
- cd com.avojak.webapp.p2.inspector.releng

script:
- mvn clean verify coveralls:report &&
  cd .. &&
  docker build --tag avojak/p2-inspector:2.0.0-SNAPSHOT --tag avojak/p2-inspector:latest . &&
  docker tag avojak/p2-inspector:latest registry.heroku.com/p2-inspector/web

deploy:
  provider: script
  skip_cleanup: true
  script:
    # Push to Docker Hub and Heroku, then perform the Heroku release
    docker push avojak/p2-inspector:2.0.0-SNAPSHOT;
    docker push avojak/p2-inspector:latest;
    docker push registry.heroku.com/p2-inspector/web;
    heroku container:release web --app p2-inspector
  on:
    branch: master
